### ISSUE TITLE
I got this error after the update

### ISSUE THREAD

**Issue by jreced** [alfonsojon/roblox-linux-wrapper#68]
fatal: Not a git repository (or any of the parent directories): .git

It also says I need to install Wine or wine-staging even though I have both installed.

**Comment by GLolol** [comment]
..Um, I may have broken something in the last update. Working on a fix now.

**Comment by GLolol** [comment]
I've reverted the changes I've made, temporarily fixing this.

@alfonsojon There are some git specific things in my changes that broke direct execution via wget. I'm reverting them now. For stability purposes (since we're dealing with multiple files), maybe it might be beneficial to *require* a `git clone` for the script to work. After all, git is already a dependency.

Sorry for making a mess :(

**Comment by alfonsojon** [comment]
That's okay, glad you reverted. Thanks for the effort anyways!

**Comment by GLolol** [comment]
I'll work out the kinks and everything tomorrow (I promise). I have to sleep...

**Comment by GLolol** [comment]
@jreced This should be fixed now. If it still does not work, try removing the RLW directory: `rm -r ~/.rlw`, and redownload the script.
