### ISSUE TITLE
Cairo-Dock cuts off Studio

### ISSUE THREAD

**Issue by eprent** [alfonsojon/roblox-linux-wrapper#76]
Likely a Wine bug because of resizing, however it completely cuts off the bottom. 

I haven't blamed Cairo-Dock for the bug yet because:
1. Everything else works
2. Even when you resize Studio it still does it (look in photos)

Photo album of it happening:
http://imgur.com/a/UVSk3

**Comment by GLolol** [comment]
RLW is a simple-ish wrapper around Wine; we don't fiddle much with graphics settings ourselves. That said, could you post the following details?

* Wine version (run `wine --version` in a terminal to find it)
* OS name and version
* Graphics card model and driver used

**Comment by eprent** [comment]
Wine version: wine-1.7.40 (Staging)

OS name: Ubuntu 14.04 running a modified version of Cinnamon DE

Intel HD Graphics and  whatever graphic drivers are built into Ubuntu, don't have the Intel ones because they dropped 14.04 support

**Comment by alfonsojon** [comment]
@eprent Can you try to enable autohide on the dock? While this is not a solution, it may be a good workaround. This issue seems to be between wine and cairo-dock, which neither are under our control.

**Comment by eprent** [comment]
@alfonsojon [I did this as a workaround](https://twitter.com/ItsEprent/status/588550306448875522), and is there anywhere I can contact Wine?

**Comment by alfonsojon** [comment]
@eprent https://bugs.winehq.org/

Don't report an issue unless you're *really* comfortable with debugging. They will ask very detailed questions, such as opening Cairo dock in debug mode.

**Comment by eprent** [comment]
Ok thanks @alfonsojon.

**Comment by NokiaGuy** [comment]
[Looks like an Wine update has fixed it, I can't reproduce it.](http://i.imgur.com/FGRyj00.png)

**Comment by NokiaGuy** [comment]
Actually now I see what's happening - When re-arranging the docks for items in Studio (explorer, properties, toolbox, etc) some of them have minimum sizes.

So people on lower resolution displays will have it push down Studio to properly fit in the docks, the Mac version has a fix to this, but obviously not the Windows version (which is what Wine is).

The general way to patch it since it's ROBLOX's fault is to re-arrange it into a manner that won't push it down.
